### ISSUE TITLE
compatible terraform version 

### ISSUE THREAD

**Issue by adityashewale** [pyToshka/terraform-provider-virtualbox#13]
which terraform version is compatible .

**Comment by pyToshka** [comment]
@adityashewale 
I tested on terraform 11 and 12

**Comment by adityashewale** [comment]
can you share me the steps i tried with 13 and 14

**Comment by pyToshka** [comment]
@adityashewale  i didnt test provider for 13 or 14, please check official terraform documentation. 
Issue closed.

**Comment by adityashewale** [comment]
I tried with 13 and 14 its not working. With 11 and 12 there is computability issue is there .

**Comment by pyToshka** [comment]
@adityashewale  if you believe the issue in provider need to share log, please in separate ticket if you double check documentation and official site.
Also feel free to ping maintainers https://github.com/terra-farm/terraform-provider-virtualbox
Thank you.
