### ISSUE TITLE
restart of all machines an apply

### ISSUE THREAD

**Issue by snapo** [pyToshka/terraform-provider-virtualbox#9]
I did notice that after a terraform apply, all VM's get restartet even if there is no change on some.

TF File

```
resource "virtualbox_vm" "worker" {
    count = 2
    name = "${format("worker-%02d", count.index+1)}"
    url = "https://vagrantcloud.com/ubuntu/boxes/bionic64/versions/20180802.0.0/providers/virtualbox.box"
    image = "./virtualbox-ubuntu.box"
    cpus = 2
    memory = "1024 mib",
    user_data = "${file("user_data")}"

    network_adapter {
        type = "bridged",
        host_interface = "Intel(R) I211 Gigabit Network Connection #2",

    }


}

output "IPAddrWorker" {
    value = "${join(",", virtualbox_vm.worker.*.network_adapter.0.ipv4_address)}"
}
```

Extending the count of the VM's to 3 should not stop all VM's and start them again...
It should (in what i expect) only create the 3rd. VM and leave the 2 existing running.

**Comment by snapo** [comment]
Created 2 TF Files as i want to create a docker swarm cluster...

File1 master.tf
```
resource "virtualbox_vm" "master" {
    count = 3
    name = "${format("master-%02d", count.index+1)}"
    url = "https://vagrantcloud.com/ubuntu/boxes/bionic64/versions/20180802.0.0/providers/virtualbox.box"
    image = "./virtualbox-ubuntu.box"
    cpus = 1
    memory = "512 mib",
    user_data = "${file("user_data")}"

    network_adapter {
        type = "bridged",
        host_interface = "Intel(R) I211 Gigabit Network Connection #2",

    }


}

output "IPAddrMaster" {
    value = "${join(",", virtualbox_vm.master.*.network_adapter.0.ipv4_address)}"
}
```


File2 worker.tf
```
resource "virtualbox_vm" "worker" {
    count = 8
    name = "${format("worker-%02d", count.index+1)}"
    url = "https://vagrantcloud.com/ubuntu/boxes/bionic64/versions/20180802.0.0/providers/virtualbox.box"
    image = "./virtualbox-ubuntu.box"
    cpus = 2
    memory = "1024 mib",
    user_data = "${file("user_data")}"

    network_adapter {
        type = "bridged",
        host_interface = "Intel(R) I211 Gigabit Network Connection #2",

    }


}

output "IPAddrWorker" {
    value = "${join(",", virtualbox_vm.worker.*.network_adapter.0.ipv4_address)}"
}


```

As soon as i add a fourth master and make terraform apply it restarts all VM's but correctly creates the new one.

DebugLog: [https://gist.github.com/snapo/c869a5a592665f4852e8b88d99365772](https://gist.github.com/snapo/c869a5a592665f4852e8b88d99365772)

I cant use it currently as i cant test adding / removing master nodes where at least 3 have to be up to be fully redundant. Any help appreciated.

**Comment by snapo** [comment]
Just saw that it is on the todo list... sorry :-(

**Comment by pyToshka** [comment]
@snapo I think i will implement this after terraform release

**Comment by Voronenko** [comment]
Does it require specific OS or box images?  
For me (18.04 LTS, VirtualBox 6.0.0.*) it fails to boot any example.

**Comment by pyToshka** [comment]
@Voronenko Did you try https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/20180206.0.0/providers/virtualbox.box
?
Ubuntu 18.04 contains extra disks and right now I haven't right solution for this problem.
For testing I using some vagrant provider, but it is pre-alfa

**Comment by Voronenko** [comment]
@pyToshka  I went with a very pervertive way so far: using ansible molecule to get fleet up  - i.e. I am reusing their way to get needed vagrant fleet up and provision.

```
https://molecule.readthedocs.io/en/latest/
```

And tune it into terraform as a null provider.

**Comment by pyToshka** [comment]
@Voronenko  
I using terraform-vagrant provider as alternative
